### PR TITLE
Multimenus

### PR DESCRIPTION
**Pull request by arm1e**
New multi menu version to make thins simpler now that there are 50+ applications

### CODE REVIEW

**Comment by arm1e** [comment]
After finishing in one category, returns to menu to select a different one or choose to exit

**Review by dasgeekchannel — COMMENTED** [review]
I like the idea here. It's really cool. However, going through menus to pick software just adds extra steps. It would be great though if we could get all the apps into category headers - so section headers and reorganizing the software within the sections of a single menu.

**Comment by arm1e** [comment]
I agree about the extra steps, but it does mean you don't need to renumber everything once you add something. The only way to prevent this atm is to just add things to the end, but this means there is no ordering.
Catch-22 I think. Are the extra steps the lesser of 2 evils?

**Comment by RiderExMachina** [comment]
I agree with @arm1e; menus are the way to go. However, (and IMO) the only way you'll end up being efficient with menus is by using a GUI.

**Comment by dasgeekchannel** [comment]
Code has been updated with new packages. Purpose to keep this simple with menu system.

**Pull request closed without merging**
