### PR TITLE
Add Docker

### PR DESCRIPTION
**Pull request by mclark4386**
This will add docker install for us devs/dev ops.

### CODE REVIEW

**Comment by dasgeekchannel** [comment]
Could not get it to install. Receiving this error:
W: Skipping acquire of configured file '\/binary-amd64/Packages' as repository 'https://download.docker.com/linux/ubuntu bionic InRelease' doesn't have the component '\' (component misspelt in sources.list?)
W: Skipping acquire of configured file '\/i18n/Translation-en' as repository 'https://download.docker.com/linux/ubuntu bionic InRelease' doesn't have the component '\' (component misspelt in sources.list?)
W: Skipping acquire of configured file '\/i18n/Translation-en_US' as repository 'https://download.docker.com/linux/ubuntu bionic InRelease' doesn't have the component '\' (component misspelt in sources.list?)
W: Skipping acquire of configured file '\/dep11/Components-amd64.yml' as repository 'https://download.docker.com/linux/ubuntu bionic InRelease' doesn't have the component '\' (component misspelt in sources.list?)
W: Skipping acquire of configured file '\/dep11/icons-48x48.tar' as repository 'https://download.docker.com/linux/ubuntu bionic InRelease' doesn't have the component '\' (component misspelt in sources.list?)
W: Skipping acquire of configured file '\/dep11/icons-64x64.tar' as repository 'https://download.docker.com/linux/ubuntu bionic InRelease' doesn't have the component '\' (component misspelt in sources.list?)
W: Skipping acquire of configured file '\/cnf/Commands-amd64' as repository 'https://download.docker.com/linux/ubuntu bionic InRelease' doesn't have the component '\' (component misspelt in sources.list?)

**Comment by RiderExMachina** [comment]
@dasgeekchannel This is because you need to edit your `/etc/apt/sources.list`. Make sure you have a line that reads `deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable` and if you don't, edit the line so it does.

**Comment by RiderExMachina** [comment]
@mclark4386 I would make the following changes:
```
echo "Installing Docker"
				apt-get install apt-transport-https ca-certificates curl software-properties-common
				curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
				echo "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list`
				apt-get update
				apt-get install docker-ce -y
```

**Comment by mclark4386** [comment]
hmm... new format... will move it to that format

**Comment by mclark4386** [comment]
should be good to go @dasgeekchannel ^^

**Comment by RiderExMachina** [comment]
Kind of. [It's a better format](https://www.reddit.com/r/linux4noobs/comments/9bxsg9/lptysk_you_can_make_installing_extra_programs/) overall, IMO.

**Comment by mclark4386** [comment]
@RiderExMachina ?

**Comment by RiderExMachina** [comment]
I may have misunderstood your post. never mind.

**Review by dasgeekchannel — APPROVED** [review]
Looks great, thank you for the contribution.

**Comment by mclark4386** [comment]
@dasgeekchannel thanks for the merge and thanks @RiderExMachina  for pointing out that method of adding the source^^

**Pull request merged**
